
# This file is automatically generated during the generation of setup.py
# Copyright 2020, Caer
author = 'Jason Dsouza <jasmcaus@gmail.com>'
version = '1.8.5'
full_version = '1.8.5'
release = True
contributors = ['Jason Dsouza <jasmcaus@gmail.com>']
