#pylint:disable=syntax-error

# This file is automatically generated during the generation of setup.py
# Copyright 2020, Caer


author = 'Ja'
version = '0.1.1'
full_version = '.1.1'
release = True
contributors = 
'Development Status :: 3 - Alpha',
'Intended Audience :: Developers',
'Intended Audience :: Education',
'Intended Audience :: Science/Research',
'Programming Language :: Python :: 3',
'Programming Language :: Python :: 3 :: Only',
'Programming Language :: Python :: 3.5',
'Programming Language :: Python :: 3.6',
'Programming Language :: Python :: 3.7',
'Programming Language :: Python :: 3.8',
'Operating System :: MacOS :: MacOS X',
'Operating System :: Microsoft :: Windows',
'License :: OSI Approved :: MIT License'
