# Builds the 'Win32' Python wheels for Caer 

name: Windows Package (x86)

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        py-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.py-version }}
      uses: actions/setup-python@v2
      with:
        architecture: 'x86'
        python-version: ${{ matrix.py-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine numpy

    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py bdist_wheel
        twine upload dist/*